apiVersion: v1
kind: Secret
metadata:
  name: unifiaap-secrets
  namespace: unifiappay
  labels:
    app: unifiaap-pay
type: Opaque
stringData:
  # Esses valores virão do Terraform output
  # Atualize após terraform apply
  DB_HOST: "unifiaap-pay-dev-rds.cvudn8tvdtb7.us-east-1.rds.amazonaws.com"
  DB_USER: "pixuser"
  DB_PASSWORD: "UniFIAPPay2025!"
  API_SECRET_KEY: "unifiaap-secret-key-2024"