apiVersion: v1
kind: Secret
metadata:
  name: unifiaap-secrets
  namespace: unifiappay
  labels:
    app: unifiaap-pay
type: Opaque
stringData:
  # Esses valores virão do Terraform output
  # Atualize após terraform apply
  DB_HOST: "TERRAFORM_OUTPUT_RDS_ENDPOINT"
  DB_USER: "pixuser"
  DB_PASSWORD: "SuaSenhaAqui123!"
  API_SECRET_KEY: "unifiaap-secret-key-2024"