---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unifiaap-api-sa
  namespace: unifiappay
  labels:
    app: unifiaap-pay

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unifiaap-audit-sa
  namespace: unifiappay
  labels:
    app: unifiaap-audit

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unifiaap-api-role
  namespace: unifiappay
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: unifiaap-api-rolebinding
  namespace: unifiappay
subjects:
- kind: ServiceAccount
  name: unifiaap-api-sa
roleRef:
  kind: Role
  name: unifiaap-api-role
  apiGroup: rbac.authorization.k8s.io